HomeScreen
benderje26/QuizzingApp341 pull request #17
Opened 2024-10-25 22:40 UTC by ZafeerurRahim

The home screen would have navigation that is the buttons work navigating the user to their desired place.

2024-10-29 01:41 UTC, benderje26 requested changes
The things with "QuizzingApp341 - Backup.csproj" and "QuizzingApp341.csprog" need to be addressed, it might be as simple as deleting QuizzingApp341.csproj and then renaming the backup to QuizzingApp341.csproj, not sure.

2024-10-29 01:41 UTC, benderje26 commented on QuizzingApp341 - Backup.csproj
I don't think this backup file should be here

2024-10-29 01:41 UTC, benderje26 commented on QuizzingApp341.csproj
And this probably should stay as views, not pages, I don't know if either of these files should've gotten changed except for the things that have to do with TestQuiz.xaml and TestQuiz.xaml.cs. The rest just seems like it is things that went wrong with downloading these from git

2024-10-29 01:41 UTC, benderje26 commented on Views/HomeScreen.xaml.cs
looks good

2024-10-29 01:41 UTC, benderje26 commented on Views/TestQuiz.xaml
looks good

2024-10-29 01:41 UTC, benderje26 commented on Views/TestQuiz.xaml.cs
looks good

2024-10-29 23:15 UTC, skogmanpe40 approved these changes
Everything ran properly for me, so approving pull request so we can try and get main up to date with all the code so we can get everything done for tomorrow

2024-10-30 13:12 UTC, benderje26 approved these changes
Looks good other than adding supabase-csharp but I'll just remove that next  commit

2024-10-30 13:12 UTC, merged